# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 246e3675d9e54d528640706890c3014ec5122af7f05734f3fcb43663f08530704d451de15855134fc47d386e31617465efab53e47760728c3ea17ca44dd460f8

test:
  secret_key_base: d0d2197a893c72f06d56bd750d7ca050b1c6fccaeee54f227c9482afefc018c8c8e71cb30de77e9f074289ef6d381944c9e5f4de444ac8be5f62b805728f8611

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
